### ISSUE TITLE
pyAMReX_Targets.cmake not being generated

### ISSUE THREAD

**Issue by archermarx** [AMReX-Codes/pyamrex#252]
Hi,

I'm trying to use an internal version of pyAMReX for my WarpX install. When I install WarpX, it finds pyAMReX, but has the following error:

```
CMake Error at /home/marksta/src/pyamrex/build/pyAMReXConfig.cmake:45 (include):
  include could not find requested file:

    /home/marksta/src/pyamrex/build/pyAMReXTargets.cmake
Call Stack (most recent call first):
  cmake/dependencies/pyAMReX.cmake:67 (find_package)
  cmake/dependencies/pyAMReX.cmake:86 (find_pyamrex)
  CMakeLists.txt:210 (include)
```

Here's my install script for pyAMReX. Note that I have AMReX installed and that pyAMReX correctly finds it, and completes the install without error.

```
cmake -S . -B build \
        -DAMReX_SPACEDIM="1;2;3" \
        -DAMReX_OMP=ON \
        -DAMReX_GPU_BACKEND=CUDA \
        -DAMReX_MPI=ON \
        -DPYINSTALLOPTIONS="--force-reinstall" \
        -DpyAMReX_amrex_internal=OFF \
        -DpyAMReX_pybind11_internal=OFF

cmake --build build -j 4 --target pip_install
```

Thanks in advance!

**Comment by ax3l** [comment]
Hi @archermarx,

Thanks for reaching out!
If you use WarpX with `-DpyAMReX_amrex_internal=OFF`, then you need to pre-install AMReX and pyAMReX manually (or get them from a package manager).
https://warpx.readthedocs.io/en/latest/developers/local_compile.html#compiling-with-pre-compiled-dependencies

You can generally do this for any dependency of WarpX, if desired:
https://warpx.readthedocs.io/en/latest/install/dependencies.html#install-dependencies
but we generally recommend to rely on package managers and/or HPC modules for this, to keep dependencies under control and builds productive and reproducible.

There are a few important compile-time options we need from AMReX, which you can find here:
https://github.com/ECP-WarpX/WarpX/blob/24.02/cmake/dependencies/AMReX.cmake#L23-L133

Most importantly, a Python install needs a **shared AMReX library**.
Additionally, WarpX, pyAMReX and AMReX go pretty lock-step in their versions - we move fast and break APIs. So make sure to always use matching versions (also documented in `cmake/dependencies/` inside WarpX).

This would be the full logic for, e.g., a WarpX 1D-3D + MPI + CUDA build, without embedded boundaries:

### Prepare Directories
Adjust as needed
```bash
# install locations
SW_DIR="$HOME/sw/warpx-gpu"
rm -rf ${SW_DIR}
mkdir -p ${SW_DIR}

# fast, temporary build directory
build_dir=$(mktemp -d)

# source directories
SRC_DIR=${HOME}/src
mkdir ${SRC_DIR}
```

### Prepare Environment Hints
We will need this to build pyAMReX and WarpX, because we install into `SW_DIR`, which is not a system-wide default path:
```bash
export CMAKE_PREFIX_PATH=${SW_DIR}/amrex-24.02:${SW_DIR}/pyamrex-24.02:${CMAKE_PREFIX_PATH}
```
This is essentially the hint to `find_package` in CMake. We hint the root directories where we installed to (essentially `CMAKE_INSTALL_PREFIX` of each project). During install, CMake place(d) the  `pyAMReXConfig.cmake` and corresponding files like `pyAMReXTargets.cmake` into the standardized locations inside it. [[1]](https://hsf-training.github.io/hsf-training-cmake-webpage/09-findingpackages/index.html) [[2]](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure)

At WarpX runtime, we will need this hint to find shared libraries of dependencies. For the small example here, the shared AMReX libs:
```bash
export LD_LIBRARY_PATH=${SW_DIR}/amrex-24.02/lib:${LD_LIBRARY_PATH}
```
Note: on some systems this is `lib64` instead of `lib`.

Below, we will create a virtual environment. Reactivate it together with the other env hints if you close your terminal at some point in the future:
```bash
source ${SW_DIR}/venvs/warpx-gpu/bin/activate
```

### Install AMReX
```bash
git clone -b 24.02 https://github.com/AMReX-Codes/amrex.git $HOME/src/amrex

cmake -S ${SRC_DIR}/amrex -B ${build_dir}/amrex  \
  -DAMReX_SPACEDIM="1;2;3"   \
  -DAMReX_GPU_BACKEND=CUDA  \
  -DAMReX_OMP=OFF  \
  -DAMReX_EB=OFF  \
  -DAMReX_FORTRAN=OFF  \
  -DAMReX_PARTICLES=ON  \
  -DAMReX_TINY_PROFILE=ON  \
  -DAMReX_PIC=ON  \
  -DBUILD_SHARED_LIBS=ON  \
  -DCMAKE_INSTALL_PREFIX=${SW_DIR}/amrex-24.02

cmake --build ${build_dir}/amrex --target install -j 12
rm -rf ${build_dir}/amrex
```

### Install pyAMReX
```bash
python3 -m pip install -U pip
python3 -m pip install --upgrade virtualenv

# prepare a virtual environment for cleanliness, activate it again later
python3 -m pip cache purge
rm -rf ${SW_DIR}/venvs/warpx-gpu
python3 -m venv ${SW_DIR}/venvs/warpx-gpu
source ${SW_DIR}/venvs/warpx-gpu/bin/activate

python3 -m pip install -U pip
python3 -m pip install -U build packaging setuptools wheel
python3 -m pip install --upgrade numpy

python3 -m pip install --upgrade mpi4py --no-cache-dir --no-build-isolation --no-binary mpi4py
```

Note: the next step needs a bug fix: #256
```bash
git clone -b 24.02 https://github.com/AMReX-Codes/pyamrex.git ${SRC_DIR}/pyamrex

cmake -S ${SRC_DIR}/pyamrex -B ${build_dir}/pyamrex  \
  -DCMAKE_INSTALL_PREFIX=${SW_DIR}/pyamrex-24.02  \
  -DpyAMReX_amrex_internal=OFF  \
  -DPython_EXECUTABLE=$(which python3)

cmake --build ${build_dir}/pyamrex --target install -j 12
cmake --build ${build_dir}/pyamrex --target pip_install -j 12
rm -rf ${build_dir}/pyamrex
```

### Install WarpX
Note: the next step needs a bug fix: https://github.com/ECP-WarpX/WarpX/pull/4668
```bash
git clone -b 24.02 https://github.com/ECP-WarpX/WarpX.git ${SRC_DIR}/warpx

cmake -S ${SRC_DIR}/warpx -B ${build_dir}/warpx  \
  -DCMAKE_INSTALL_PREFIX=${SW_DIR}/warpx-24.02  \
  -DPython_EXECUTABLE=$(which python3)  \
  -DWarpX_DIMS="1;2;RZ;3"  \
  -DWarpX_COMPUTE=CUDA  \
  -DWarpX_PYTHON=ON  \
  -DWarpX_amrex_internal=OFF  \
  -DWarpX_pyamrex_internal=OFF

cmake --build ${build_dir}/warpx --target install -j 12
cmake --build ${build_dir}/warpx --target pip_install -j 12
rm -rf ${build_dir}/warpx
```

**Comment by ax3l** [comment]
That said, can I ask you about your use case to guide you better? :)

We intentionally do the superbuild in WarpX, because then **developers and users** do not need to worry about configuring and maintaining the right matching versions of AMReX and pyAMReX.
https://warpx.readthedocs.io/en/latest/install/cmake.html

If you are also aiming at **rapid developing**, while changing WarpX, AMReX and pyAMReX _at the same time_, consider the following easier options, including the `-DWarpX_<dependency>_src=<local-path>` option and providing tools such as CCache for fast iterations in your build process:
https://warpx.readthedocs.io/en/latest/developers/local_compile.html#compiling-with-pre-compiled-dependencies

We of course disable this in **package managers**, so we can maintain individual versions. So you can also, when developing only on WarpX, pre-install e.g., our AMReX and pyAMReX conda packages and other dependencies, similar to here:
https://warpx.readthedocs.io/en/latest/install/dependencies.html#conda-linux-macos-windows

You can also do the same with Spack, but I still have to finalize a new `py-amrex` package for that and submit it for inclusion.

**Comment by archermarx** [comment]
Thanks for the detailed response! I'm trying to modify WarpX locally and would like to have as many of the dependencies pre-built as possible to speed up re-compilation. I think I was missing the shared library bit, so I will attempt that and report back!

**Comment by ax3l** [comment]
Awesome!

In that case I would either do one of:
- [developer dependencies](https://warpx.readthedocs.io/en/latest/install/dependencies.html#conda-linux-macos-windows) + `..._src` for pyAMReX/AMReX and CCache everything after the first build or
- same developer dependencies + pyAMReX + AMReX prebuilt from Conda, build WarpX w/ all `..._internal=OFF` & still w/ CCache for WarpX

**Comment by archermarx** [comment]
Hi Axel,

Does the conda version of AMReX support CUDA?

**Comment by ax3l** [comment]
Ah, AMReX and pyAMReX are not yet with CUDA on conda-forge: https://github.com/conda-forge/amrex-feedstock/issues/4
But everything else does not need CUDA, so the above link still works (and you could install AMReX & pyAMReX into the `$CONDA_PREFIX` as install prefix.

For CUDA you could pre build via Spack packages (not yet pyamrex, probably 24.03+ will be there).

**Comment by archermarx** [comment]
Thanks for your help! I think we can close this issue then!
